/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-doa
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_DOA_API_H
#define INCLUDED_DOA_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_doa_EXPORTS
#define DOA_API __GR_ATTR_EXPORT
#else
#define DOA_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_DOA_API_H */
