/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */
#include "pydoc_macros.h"
#define D(...) DOC(gr, doa, __VA_ARGS__)
/*
  This file contains docstrings for the Python bindings.
  Do not edit! These were automatically extracted during the binding process
  and will be overwritten during the build process
 */



 static const char *__doc_gr_doa_antenna_correction = R"doc(
Antenna Correction Block.

This block uses antenna gain and phase values stored in a config file 
to scale the input signals such that the response of the antennas in 
the array are homogenous.
)doc";


 static const char *__doc_gr_doa_antenna_correction_antenna_correction_0 = R"doc(
Constructor for the antenna correction block.
)doc";


 static const char *__doc_gr_doa_antenna_correction_make = R"doc(
Make an antenna correction block.

Parameters:
    num_ant_ele : Number of antenna elements
    config_filename : Config file that has been generated by one of the antenna calibration blocks
)doc";
