/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(power_detection_cpp.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(73964bcb4ae84e7562a79e60ca0cd9c4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/doa/power_detection_cpp.h>
// pydoc.h is automatically generated in the build directory
#include <power_detection_cpp_pydoc.h>

void bind_power_detection_cpp(py::module& m)
{

    using power_detection_cpp = ::gr::doa::power_detection_cpp;


    py::class_<power_detection_cpp,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<power_detection_cpp>>(
        m, "power_detection_cpp", D(power_detection_cpp))

        .def(py::init(&power_detection_cpp::make),
             py::arg("num_inputs"),
             py::arg("sample_rate"),
             py::arg("buffer_size") = 1024,
             py::arg("threshold_multiplier") = 5.F,
             D(power_detection_cpp, make))


        ;
}
