/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(signal_replay_cpp.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(076f541c0aef63c3d4c3d58cd3788907)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/doa/signal_replay_cpp.h>
#include "signal_replay_cpp_pydoc.h"

#ifndef DOC
#define DOC(x) __doc_##x
#endif

void bind_signal_replay_cpp(py::module& m)
{
    using signal_replay_cpp = ::gr::doa::signal_replay_cpp;

    py::class_<signal_replay_cpp,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<signal_replay_cpp>>(
        m, "signal_replay_cpp", DOC(signal_replay_cpp))

        .def(py::init(&signal_replay_cpp::make),
             py::arg("filename"),
             py::arg("repeat") = true,
             py::arg("interpolation") = 1,
             DOC(signal_replay_cpp_make))
        ;
}
